- type: gameMapPool
  id: DefaultMapPool
  maps:
#PIRATE START
  - Atlas
  - Aspid
  - Bagel
  # - Barratry
  - Box
  - Cluster
  #- Core
  #- Fland
  #- Kettle
  - Marathon
  #- Meta
  - Omega
  # - Origin
  - Saltern
  - Packed
#PIRATE END
# DeltaV
  - Arena
  - Asterisk
  - Edge
  - Hammurabi
  - Lighthouse
  - Pebble
  - Shoukou
  - Tortuga
  - TheHive
  - Submarine
